version: "3.7"
services:
  influx:
    image: influxdb:1.7
    environment:
      - INFLUXDB_DB=rails
      - INFLUXDB_USER=rails
      - INFLUXDB_USER_PASSWORD=rails
      - INFLUXDB_READ_USER=grafana
      - INFLUXDB_READ_USER_PASSWORD=grafana
    volumes:
      - influxdata:/var/lib/influxdb
    ports:
      - 8086:8086
  grafana:
    image: grafana/grafana:6.2.4
    ports:
      - 8000:3000
    depends_on:
      - influx
    volumes:
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/grafana-datasource.yml:ro
      - grafanadata:/var/lib/grafana
volumes:
  influxdata:
  grafanadata:
